name: work39_torch2
channels:
  - tensorly
  - pytorch3d
  - pytorch
  - nvidia
  - huggingface
  - conda-forge
dependencies:
  - python>=3.9, <3.10
  - pytorch=2.1.1
  - pytorch-cuda=12.1
  - torchaudio=2.1.1
  - torchvision=0.16.1
  - librosa=0.9.2
  - loguru=0.6.0
  # - onnx=1.10.2
  - onnx2torch=1.5
  - pandas=1.4.2
  - pip=21.2.4
  - pyopengl=3.1
  - pyrender=0.1.45
  - pyvista=0.35
  # - pyvistaqt=0.10
  - pyvistaqt
  - resampy=0.2.2
  - scikit-image=0.19.2
  - scikit-learn=1.0.2
  # - scikit-video=1.1.11 ## install with pip from github to stop the crash with new numpy
  - seaborn=0.11.0
  - tensorly=0.6.0
  - ffmpeg-python=0.2.0
  - plotly=5.19.0
  - pip:
    - albumentations==1.0.3
    - compress-pickle==1.2.0
    # - chumpy==0.70
    - chumpy @ git+https://github.com/mattloper/chumpy.git #0.71
    # - Cython==0.29
    - Cython==3.0.7
    - decord==0.6.0
    - face-alignment==1.3.5
    - facenet-pytorch==2.5.2
    - gdown==4.5.1
    - h5py==3.8.0
    - hickle==5.0.2
    # - huggingface-hub==0.20
    # - hydra-core==1.0.7
    - hydra-core==1.3.2
    - imgaug==0.4.0
    - insightface==0.6.2
    - kornia==0.6.5
    - matplotlib==3.2.2
    - mediapipe==0.8.10
    - munch==2.5.0
    # - numpy==1.23.0
    - numpy==1.26.2
    - onnx==1.15
    - onnxruntime-gpu==1.16.2
    - opencv-contrib-python==4.9.0.80
    - opencv-python==4.9.0.80
    - opencv-python-headless==4.9.0.80
    - psbody-mesh @ git+https://github.com/radekd91/mesh.git@fix/openGLunavailable
    - python-speech-features==0.6
    # - pytorch-lightning==1.4.9
    - pytorch-lightning==1.9
    - pytorch3d @ git+https://github.com/facebookresearch/pytorch3d.git # as of 15th of Jan 2024 necessary, 0.7.6 in the future
    - torchgeometry==0.1.2
    # - torchmetrics==0.6.2
    - torchfile==0.1.0
    - transformers==4.36.2
    - trimesh==4.0.8
    - wandb==0.10.33
    # - protobuf==0.13.0


